### ISSUE TITLE
[BUG] external_ids GRID id is not in an array in "all" node

### ISSUE THREAD

**Issue by CopyCat73** [ror-community/ror-roadmap#210]
**Describe the bug**
All identifiers are in the JSON node "all" for each type. All types have an array, except for the grid type. My code iterates through the "all" list, but since the grid list is not actually  an array, it is split up in individual letters. Please correct it so that the grid id is also in a json array.  

**To Reproduce**
1. Go to json dump
2. Open document, scroll down to external_ids in first record:

            "Wikidata": {
                "preferred": null,
                "all": [
                    "Q741082"
                ]
            },
            "GRID": {
                "preferred": "grid.1004.5",
                "all": "grid.1004.5"
            }

Wikidata all field is array, grid is not. 

**Expected behavior**
grid id should be in json array.

**Comment by amandafrench** [comment]
@CopyCat73 Have you considered using v2 of the ROR schema in your Pure integration? This inconsistency is something we inherited from GRID, and it's one of the things that's fixed in v2. More information here: https://ror.readme.io/docs/ror-schema-api-v2-beta -- it's due to be released by the end of March, so not too much longer. 

It is an annoyance, but we don't plan to fix it in v1, since it's fixed in v2 of the API and schema.

**Comment by lizkrznarich** [comment]
Closing now that v2 is on production and this issue is fixed there.
